version: '2'
services:
  wordpress:
    image: coomy/wp:latest
    links:
      - db
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./app/plugins/wd:/app/wp-content/plugins/wd # Plugin development
      - ./app/themes/wd:/app/wp-content/themes/wd # Plugin development
    environment:
      DB_NAME: tests
      DB_PASS: root
      PLUGINS: >-
        akismet,
        sidekick
      DEVELOPMENT_FOLDER: wd
  db:
    image: mysql:5.7 # or mariadb
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}
